version: 0.2

phases:
  install:
    commands:
      - curl -o packer.zip https://releases.hashicorp.com/packer/1.8.5/packer_1.8.5_linux_amd64.zip
      - unzip packer.zip
      - sudo mv packer /usr/local/bin/
  build:
    commands:
      - packer init .
      - packer build .
artifacts:
  files:
    - '*'